### ISSUE TITLE
Inconsistencies in the navigation and main menu

### ISSUE THREAD

**Issue by hmariann** [geryxyz/iFL-research#2]
In the NAVIGATION menu on the left there are four items: Home, Introduction, Publications, Supplementary Material, while in the main menu at the top only three: Home, Publications, Data. "Introduction" is missing and "Data" is inconsistent with the name "Supplementary Material" in the navigation bar (but they link to the same page). These two menus could be synchronized.

**Comment by geryxyz** [comment]
@hmariann f5d26e2

**Comment by hmariann** [comment]
A hiba javítva lett.
